CCFLAGS += -DMAX_DSPS="$(TI_DSPLINK_MAX_DSPS)"
CCFLAGS += -DID_GPP="$(TI_DSPLINK_ID_GPP)"
CCFLAGS += -DMAX_PROCESSORS="$(TI_DSPLINK_MAX_PROCESSORS)"

#CCFLAGS += -g

#some common defines
#############################################################
CCFLAGS += -DOS_QNX6
CCFLAGS += -DNO_SMP
CCFLAGS += -DTRACE_KERNEL
CCFLAGS += -DKFILE_DEFAULT
CCFLAGS += -DDSP_COMPONENT


#pick defines from CURRENTCFG.MK
##############################################################
ifeq ($(findstring DRA44XGEM, $(TI_DSPLINK_DSPDEVICES)), DRA44XGEM)
CCFLAGS += -DDRA44XGEM
endif
ifeq ($(findstring OMAP3530, $(TI_DSPLINK_DSPDEVICES)), OMAP3530)
CCFLAGS += -DOMAP3530
endif
ifeq ($(findstring DA8XXGEM, $(TI_DSPLINK_DSPDEVICES)), DA8XXGEM)
CCFLAGS += -DDA8XXGEM
endif

ifeq ($(TI_DSPLINK_USE_PROC), 1)
CCFLAGS += -DPROC_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_POOL), 1)
CCFLAGS += -DPOOL_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_NOTIFY), 1)
CCFLAGS += -DNOTIFY_COMPONENT
endif
ifeq ($(TI_DSPLINK_USE_MPCS), 1)
CCFLAGS += -DMPCS_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_RINGIO), 1)
CCFLAGS += -DRINGIO_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_MPLIST), 1)
CCFLAGS += -DMPLIST_COMPONENT
endif
ifeq ($(TI_DSPLINK_USE_MSGQ), 1)
CCFLAGS += -DMSGQ_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_CHNL), 1)
CCFLAGS += -DCHNL_COMPONENT 
endif
ifeq ($(TI_DSPLINK_USE_MSGQ_ZCPY_LINK), 1)
CCFLAGS += -DZCPY_LINK
CCFLAGS += -DMSGQ_ZCPY_LINK  
endif
ifeq ($(TI_DSPLINK_USE_CHNL_ZCPY_LINK), 1)
CCFLAGS += -DCHNL_ZCPY_LINK 
endif
ifeq ($(TI_DSPLINK_LEGACY_SUPPORT), 1)
CCFLAGS += -DDSPLINK_LEGACY_SUPPORT
endif
ifeq ($(TI_DSPLINK_TRACE), 1)
CCFLAGS += -DTRACE_ENABLE
endif

ifeq ($(TI_DSPLINK_PLATFORM), omapl1xx )
CCFLAGS += -DTI_DSPLINK_DA8XXGEM_PHYINTERFACE="$(TI_DSPLINK_DA8XXGEM_PHYINTERFACE)"
endif

