#include <devctl.h>
#include <dsplink160/drvdefs.h>
#include <dsplink160/gpptypes.h>

#define _DCMD_DSPLINK   _DCMD_MISC

#define DCMD_UNKNOWN					__DIOTF (_DCMD_DSPLINK, 0x1,   CMD_Args)

#define DCMD_DSPLINK_DRV_GETCHNLMAPTBL	__DIOTF (_DCMD_DSPLINK, 0x301, CMD_Args)
#define DCMD_DSPLINK_PROC_POOLID		    __DIOTF (_DCMD_DSPLINK, 0x302, CMD_Args)

#define DCMD_DSPLINK_MSGQ_XPTOPEN       __DIOTF (_DCMD_DSPLINK, 0x401, CMD_Args)
#define DCMD_DSPLINK_MSGQ_XPTCLOSE      __DIOTF (_DCMD_DSPLINK, 0x402, CMD_Args)
#define DCMD_DSPLINK_MSGQ_OPEN          __DIOTF (_DCMD_DSPLINK, 0x403, CMD_Args)
#define DCMD_DSPLINK_MSGQ_CLOSE         __DIOTF (_DCMD_DSPLINK, 0x404, CMD_Args)
#define DCMD_DSPLINK_MSGQ_LOCATE        __DIOTF (_DCMD_DSPLINK, 0x405, CMD_Args)
#define DCMD_DSPLINK_MSGQ_LOCATEASYNC   __DIOTF (_DCMD_DSPLINK, 0x406, CMD_Args)
#define DCMD_DSPLINK_MSGQ_RELEASE       __DIOTF (_DCMD_DSPLINK, 0x407, CMD_Args)
#define DCMD_DSPLINK_MSGQ_ALLOC         __DIOTF (_DCMD_DSPLINK, 0x408, CMD_Args)
#define DCMD_DSPLINK_MSGQ_FREE          __DIOTF (_DCMD_DSPLINK, 0x409, CMD_Args)
#define DCMD_DSPLINK_MSGQ_PUT           __DIOTF (_DCMD_DSPLINK, 0x40a, CMD_Args)
#define DCMD_DSPLINK_MSGQ_GET           __DIOTF (_DCMD_DSPLINK, 0x40b, CMD_Args)
#define DCMD_DSPLINK_MSGQ_SETERR        __DIOTF (_DCMD_DSPLINK, 0x40c, CMD_Args)
#define DCMD_DSPLINK_MSGQ_COUNT         __DIOTF (_DCMD_DSPLINK, 0x40d, CMD_Args)
#define DCMD_DSPLINK_MSGQ_INSTR         __DIOTF (_DCMD_DSPLINK, 0x40e, CMD_Args)
#define DCMD_DSPLINK_MSGQ_DEBUG         __DIOTF (_DCMD_DSPLINK, 0x40f, CMD_Args)

#define DCMD_DSPLINK_CHNL_CREATE        __DIOTF (_DCMD_DSPLINK, 0x201, CMD_Args)
#define DCMD_DSPLINK_CHNL_DELETE        __DIOTF (_DCMD_DSPLINK, 0x202, CMD_Args)
#define DCMD_DSPLINK_CHNL_ISSUE         __DIOTF (_DCMD_DSPLINK, 0x203, CMD_Args)
#define DCMD_DSPLINK_CHNL_RECLAIM       __DIOTF (_DCMD_DSPLINK, 0x204, CMD_Args)
#define DCMD_DSPLINK_CHNL_ALLOCBUF      __DIOTF (_DCMD_DSPLINK, 0x205, CMD_Args)
#define DCMD_DSPLINK_CHNL_FREEBUF       __DIOTF (_DCMD_DSPLINK, 0x206, CMD_Args)
#define DCMD_DSPLINK_CHNL_IDLE          __DIOTF (_DCMD_DSPLINK, 0x207, CMD_Args)
#define DCMD_DSPLINK_CHNL_FLUSH         __DIOTF (_DCMD_DSPLINK, 0x208, CMD_Args)
#define DCMD_DSPLINK_CHNL_CONTROL       __DIOTF (_DCMD_DSPLINK, 0x209, CMD_Args)
#define DCMD_DSPLINK_CHNL_INSTR         __DIOTF (_DCMD_DSPLINK, 0x20a, CMD_Args)
#define DCMD_DSPLINK_CHNL_DEBUG         __DIOTF (_DCMD_DSPLINK, 0x20b, CMD_Args)

#define DCMD_DSPLINK_PROC_SETUP         __DIOTF (_DCMD_DSPLINK, 0x101, CMD_Args)
#define DCMD_DSPLINK_PROC_DESTROY       __DIOTF (_DCMD_DSPLINK, 0x102, CMD_Args)
#define DCMD_DSPLINK_PROC_START         __DIOTF (_DCMD_DSPLINK, 0x103, CMD_Args)
#define DCMD_DSPLINK_PROC_STOP          __DIOTF (_DCMD_DSPLINK, 0x104, CMD_Args)
#define DCMD_DSPLINK_PROC_LOAD          __DIOTF (_DCMD_DSPLINK, 0x105, CMD_Args)
#define DCMD_DSPLINK_PROC_LOADSEC       __DIOTF (_DCMD_DSPLINK, 0x106, CMD_Args)
#define DCMD_DSPLINK_PROC_DETACH        __DIOTF (_DCMD_DSPLINK, 0x107, CMD_Args)
#define DCMD_DSPLINK_PROC_ATTACH        __DIOTF (_DCMD_DSPLINK, 0x108, CMD_Args)
#define DCMD_DSPLINK_PROC_GETSTATE      __DIOTF (_DCMD_DSPLINK, 0x109, CMD_Args)
#define DCMD_DSPLINK_PROC_CONTROL       __DIOTF (_DCMD_DSPLINK, 0x10a, CMD_Args)
#define DCMD_DSPLINK_PROC_READ          __DIOTF (_DCMD_DSPLINK, 0x10b, CMD_Args)
#define DCMD_DSPLINK_PROC_WRITE         __DIOTF (_DCMD_DSPLINK, 0x10c, CMD_Args)
#define DCMD_DSPLINK_PROC_INSTR         __DIOTF (_DCMD_DSPLINK, 0x10d, CMD_Args)
#define DCMD_DSPLINK_PROC_DEBUG         __DIOTF (_DCMD_DSPLINK, 0x10e, CMD_Args)
#define DCMD_DSPLINK_PROC_CLEAN         __DIOTF (_DCMD_DSPLINK, 0x10f, CMD_Args)
#define DCMD_DSPLINK_PROC_ISLASTDESTROY __DIOTF (_DCMD_DSPLINK, 0x110, CMD_Args)
#define DCMD_DSPLINK_PROC_ISLASTDETACH  __DIOTF (_DCMD_DSPLINK, 0x111, CMD_Args)

#define DCMD_DSPLINK_PROBE_INIT         __DIOTF (_DCMD_DSPLINK, 0x501, CMD_Args)
#define DCMD_DSPLINK_PROBE_FINAL        __DIOTF (_DCMD_DSPLINK, 0x502, CMD_Args)

#define DCMD_DSPLINK_POOL_OPEN          __DIOTF (_DCMD_DSPLINK, 0x601, CMD_Args)
#define DCMD_DSPLINK_POOL_CLOSE         __DIOTF (_DCMD_DSPLINK, 0x602, CMD_Args)
#define DCMD_DSPLINK_POOL_ALLOC         __DIOTF (_DCMD_DSPLINK, 0x603, CMD_Args)
#define DCMD_DSPLINK_POOL_FREE          __DIOTF (_DCMD_DSPLINK, 0x604, CMD_Args)
#define DCMD_DSPLINK_POOL_XLATEADDR     __DIOTF (_DCMD_DSPLINK, 0x605, CMD_Args)
#define DCMD_DSPLINK_POOL_WRITEBACK		__DIOTF (_DCMD_DSPLINK, 0x606, CMD_Args)
#define DCMD_DSPLINK_POOL_INVALIDATE	__DIOTF (_DCMD_DSPLINK, 0x607, CMD_Args)

#define DCMD_DSPLINK_RINGIO_MAPREGION   __DIOTF (_DCMD_DSPLINK, 0x811, CMD_Args)
#define DCMD_DSPLINK_RINGIO_UNMAPREGION __DIOTF (_DCMD_DSPLINK, 0x812, CMD_Args)

#define DCMD_DSPLINK_MPCS_MAPREGION     __DIOTF (_DCMD_DSPLINK, 0x701, CMD_Args)
#define DCMD_DSPLINK_MPLIST_MAPREGION   __DIOTF (_DCMD_DSPLINK, 0x821, CMD_Args)

#define DCMD_DSPLINK_NOTIFY_INIT        __DIOTF (_DCMD_DSPLINK, 0x801, CMD_Args)
#define DCMD_DSPLINK_NOTIFY_FINAL       __DIOTF (_DCMD_DSPLINK, 0x802, CMD_Args)
#define DCMD_DSPLINK_NOTIFY_REGISTER    __DIOTF (_DCMD_DSPLINK, 0x803, CMD_Args)
#define DCMD_DSPLINK_NOTIFY_UNREGISTER  __DIOTF (_DCMD_DSPLINK, 0x804, CMD_Args)
#define DCMD_DSPLINK_NOTIFY_NOTIFY      __DIOTF (_DCMD_DSPLINK, 0x805, CMD_Args)

#define DCMD_DSPLINK_IDM_INIT			__DIOTF (_DCMD_DSPLINK, 0x851, CMD_Args)
#define DCMD_DSPLINK_IDM_EXIT			__DIOTF (_DCMD_DSPLINK, 0x852, CMD_Args)
#define DCMD_DSPLINK_IDM_CREATE			__DIOTF (_DCMD_DSPLINK, 0x853, CMD_Args)
#define DCMD_DSPLINK_IDM_DELETE			__DIOTF (_DCMD_DSPLINK, 0x854, CMD_Args)
#define DCMD_DSPLINK_IDM_ACQUIREID		__DIOTF (_DCMD_DSPLINK, 0x855, CMD_Args)
#define DCMD_DSPLINK_IDM_RELEASEID		__DIOTF (_DCMD_DSPLINK, 0x856, CMD_Args)

#define DCMD_DSPLINK_SYNC_CREATE		__DIOTF (_DCMD_DSPLINK, 0x900, CMD_Args)
#define DCMD_DSPLINK_SYNC_DELETE		__DIOTF (_DCMD_DSPLINK, 0x901, CMD_Args)

#define DCMD_DSPLINK_NOTIFYS_CREATE		__DIOTF (_DCMD_DSPLINK, 0x902, CMD_Args)
#define DCMD_DSPLINK_NOTIFYS_DELETE		__DIOTF (_DCMD_DSPLINK, 0x903, CMD_Args)


